{
 "title": "SmartGenerators",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Fuel (167)",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 2, "x": 1, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "litre" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(timestamp),\n  sample\nFROM fuel_level\nWHERE\n  $__timeFilter(timestamp) AND\n  machineid = 167 OR\n  machineid = 2\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Energy (167)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(timestamp),\n  sample\nFROM energy_generated\nWHERE\n  $__timeFilter(timestamp) AND\n  machineid = 167 OR\n  machineid = 2\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Fuel (248)",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 2, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "litre" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(timestamp),\n  sample\nFROM fuel_level\nWHERE\n  $__timeFilter(timestamp) AND\n  machineid = 248 OR\n  machineid = 3\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Energy (248)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(timestamp),\n  sample\nFROM energy_generated\nWHERE\n  $__timeFilter(timestamp) AND\n  machineid = 248 OR\n  machineid = 3\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Fuel (174)",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 2, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "litre" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(timestamp),\n  sample\nFROM fuel_level\nWHERE\n  $__timeFilter(timestamp) AND\n  machineid = 174 OR\n  machineid = 4\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Energy (174)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(timestamp),\n  sample\nFROM energy_generated\nWHERE\n  $__timeFilter(timestamp) AND\n  machineid = 174 OR\n  machineid = 4\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Temperature (167)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(timestamp),\n  unit AS metric,\n  sample\nFROM temperature\nWHERE\n  $__timeFilter(timestamp) AND\n  machineid = 167 OR\n  machineid = 2\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Temperature (167)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(timestamp),\n  unit AS metric,\n  sample\nFROM temperature\nWHERE\n  $__timeFilter(timestamp) AND\n  machineid = 167 OR\n  machineid = 3\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Temperature (174)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(timestamp),\n  unit AS metric,\n  sample\nFROM temperature\nWHERE\n  $__timeFilter(timestamp) AND\n  machineid = 174 OR\n  machineid = 3\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Fuel (186)",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 2, "x": 4, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "litre" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(timestamp),\n  sample\nFROM fuel_level\nWHERE\n  $__timeFilter(timestamp) AND\n  machineid = 186 OR\n  machineid = 5\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Energy (186)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 7, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(timestamp),\n  sample\nFROM energy_generated\nWHERE\n  $__timeFilter(timestamp) AND\n  machineid = 186 OR\n  machineid = 5\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Fuel (193)",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 2, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "litre" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(timestamp),\n  sample\nFROM fuel_level\nWHERE\n  $__timeFilter(timestamp) AND\n  machineid = 193 OR\n  machineid = 6\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Energy (193)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 15, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(timestamp),\n  sample\nFROM energy_generated\nWHERE\n  $__timeFilter(timestamp) AND\n  machineid = 193 OR\n  machineid = 6\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Temperature (186)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 3, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(timestamp),\n  unit AS metric,\n  sample\nFROM temperature\nWHERE\n  $__timeFilter(timestamp) AND\n  machineid = 186 OR\n  machineid = 5\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Temperature (193)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 11, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(timestamp),\n  unit AS metric,\n  sample\nFROM temperature\nWHERE\n  $__timeFilter(timestamp) AND\n  machineid = 193 OR\n  machineid = 6\nORDER BY timestamp"
    }
   ]
  }
 ]
}